# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaunt',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jaunt',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jaunt',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
