# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170405_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaunt',
            name='owner',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
