# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170405_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='original_url',
            new_name='original_path',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumbnail_url',
            new_name='thumbnail_path',
        ),
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
