# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170409_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
